CREATE TABLE `operation_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`module` enum('department','code_rule','user','language','system','product','customer','supplier','inventory','order','quality','production','finance','document') NOT NULL,
	`action` enum('create','update','delete','status_change','role_change','permission_change','import','export','login','logout','reset','approve','reject') NOT NULL,
	`targetType` varchar(50) NOT NULL,
	`targetId` varchar(50),
	`targetName` varchar(200),
	`description` text NOT NULL,
	`previousData` text,
	`newData` text,
	`changedFields` text,
	`operatorId` int NOT NULL,
	`operatorName` varchar(100) NOT NULL,
	`operatorRole` varchar(50),
	`operatorDepartment` varchar(100),
	`ipAddress` varchar(50),
	`userAgent` text,
	`deviceType` varchar(50),
	`browser` varchar(50),
	`result` enum('success','failure','partial') NOT NULL DEFAULT 'success',
	`errorMessage` text,
	`operatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `operation_logs_id` PRIMARY KEY(`id`)
);
